#!/bin/bash
pip3 install aiohttp
pip3 install async-timeout
pip3 install certifi
pip3 install cycler
pip3 install chardet
pip3 install decorator
pip3 install django
pip3 install easygui
pip3 install et-xmlfile
pip3 install fuzzywuzzy
pip3 install idna
pip3 install idna-ssl
pip3 install image
pip3 install jdcal
pip3 install joblib
pip3 install lxml
pip3 install matplotlib
pip3 install multidict
pip3 install networkx
pip3 install numpy
pip3 install opencv-contrib-python
pip3 install openpyxl
pip3 install pandas
pip3 install parse
pip3 install pillow
pip3 install pyparsing
pip3 install python-dateutil
pip3 install python-levenshtein
pip3 install pytz
pip3 install pywavelets
pip3 install requests
pip3 install requests-cache
pip3 install scikit-image
pip3 install scikit-learn
pip3 install scipy
pip3 install selenium
pip3 install six
pip3 install sklearn
pip3 install tqdm
pip3 install unidecode
pip3 install urllib3
pip3 install xlrd
pip3 install xlsxwriter
pip3 install xlwt
pip3 install yarl
pip3 install googletrans
pip3 install fuzzyset
pip3 install bs4
pip3 install textblob
pip3 install textblob-fr
pip3 install seaborn
pip3 install dask
pip3 install toolz
pip3 install cloudpickle
pip3 install image-match
pip3 install elasticsearch
pip3 install python-magic
pip3 install proxybroker
pip3 install aiosocks
pip3 install tinydb
pip3 install ujson
pip3 install sqlalchemy
pip3 install tldextract
pip3 install regex
pip3 install filetype
pip3 install pyahocorasick
pip3 install google-api-python-client
pip3 install pipfile
pip3 install xlsxwrite
